domains:
- domain: services.edu.exokomodo.com
  type: PRIMARY
name: edu
region: sfo
services:
- github:
    branch: main
    deploy_on_push: true
    repo: ExoKomodo/Edu
  envs:
    - key: MONGODB_URI
      value: EV[1:HPMvG2kCPQi0ns0IQ/rC7Xa01Gki00M4:eoLSujhbHKHi8nQc1oYYt5k5eO1S2RNhjeHOmDXo9Htijnfx0zxxuJkKA1b6+9mxIitNNqFgX8mjqPex01KcGvlcMvx+Y8jKg3vDbmfLobygBjeexY3Jeb6HR6lBVv6kUiSUJjCoGcYzsfy94QgCVvwnZ/RSoE9Rae/tvLHDAEF9yFARONNwDw==]
      scope: RUN_TIME
      type: SECRET
    - key: AUTH0_CLIENT_ID
      value: d0nbGyYvhTxPjyL1eaa3K4ojLDUNt1LX
      scope: RUN_TIME
      type: GENERAL
    - key: AUTH0_CLIENT_SECRET
      scope: RUN_TIME
      type: SECRET
      value: EV[1:EO47SfFt1n+zpt7fEgJL4jWtsYLvkjAq:L+Df+W9yMPCdYy8ZNquWR/B5WiN6JG0URWUxnpOw8FbBiKySto4VCtRxlLoEZmDVOtxN1XuGVGpfsKpp/W4ViJp1guSel/35tDeOJ1ykDzc=]
    - key: AWS_ACCESS_KEY_ID
      scope: RUN_TIME
      type: GENERAL
      value: DO00MM6Z43GZ4V6YX8PY
    - key: AWS_SECRET_ACCESS_KEY
      scope: RUN_TIME
      type: SECRET
      value: EV[1:xwsgcMt3oiyFTGMT5VJ+YAs+9edZvbuH:g7ZaHjciPUEveJAl6fA1cWkwUZV/+ZMezfy5bEoeMPmW3d+OReTCJr2KAQuh4IvKGPFHR/0ndlfXQl4=]
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: edu
  routes:
  - path: /
  dockerfile_path: server/Dockerfile
  source_dir: server
