domains:
- domain: services.edu.exokomodo.com
  type: PRIMARY
name: edu
region: sfo
services:
- github:
    branch: 19_digital-ocean
    deploy_on_push: true
    repo: ExoKomodo/Edu
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: edu
  routes:
  - path: /
  source_dir: /
  dockerfile_path: server.Dockerfile
