name: Bugs (for Exo the komodo to eat)
description: |
  Report a bug, or something that just doesn't feel quite right or intentional
title: "[BUG] <name your bug>"
labels:
  - bug
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-is-wrong
    attributes:
      label: What is wrong?
      description: |
        Explain what is happening that is not expected
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How can I, the developer, reproduce this?
      description: |
        Explain the steps you have taken to cause this bug to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Supplemental attachments?
      description: |
        Please provide provide screenshots, videos, or whatever gets your point across

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        Explain what resolution would make you consider this bug fixed
    validations:
      required: true
