name: Content Improvement
description: |
  Explain what improvement or additions you believe Edu's content should have
title: "[CONTENT] <name your content improvement here>"
labels:
  - content
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: content-improvement
    attributes:
      label: Content Improvement
      description: |
        Explain what new content you believe Edu should provide, or an improvement to the existing content's style or...well, content
    validations:
      required: true
- type: textarea
  attributes:
    label: Supplemental attachments?
    description: |
     Please provide provide screenshots, videos, or whatever gets your point across

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: textarea
  id: acceptance-criteria
  attributes:
    label: Acceptance Criteria
    description: |
      Define some kind of 'standard of completion' for this content improvement
  validations:
    required: true
