name: Client

on:
  push:
    branches:
      - main
    paths:
      - client/**
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: ./client/package-lock.json
    - name: Install dependencies
      run: |
        npm ci
    - name: Build
      run: |
        npm run build --if-present
        cp ./dist/index.html ./dist/404.html
    - name: Unit tests
      run: |
        npm run test:unit
    - name: E2E tests
      run: |
        npm run test:e2e
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./client/dist
        allow_empty_commit: false
        keep_files: false
        force_orphan: true
        cname: edu.exokomodo.com
    - name: Send status to Discord
      uses: nebularg/actions-discord-webhook@v1
      if: always()
      with:
        webhook_url: ${{ secrets.DISCORD_CI_WEBHOOK }}
        status: ${{ job.status }}
