name: Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: client/package-lock.json
        node-version-file: client/package.json

    - name: Check CLI tools
      run: |
        for tool in node npm; do
          if ! command -v $tool &> /dev/null; then
            echo "${tool} is not installed"
            exit 1
          fi
          ${tool} --version
        done

    - name: Install dependencies
      run: |
        npm ci

    - name: Build
      run: |
        npm run build --if-present
        cp ./dist/index.html ./dist/404.html

    - name: Unit tests
      run: |
        npm run test:unit

    - name: E2E tests
      run: |
        npm run test:e2e

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: client-dist
        path: client/dist

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4

    - name: Check artifact
      run: |
        ls -la client-dist
        ls -la client-dist/dist
        if [ ! -d client/dist ]; then
          echo "Artifact not found"
          exit 1
        fi

    - name: Deploy
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: client/dist
        allow_empty_commit: false
        keep_files: false
        force_orphan: true
        cname: edu.exokomodo.com

    - name: Send status to Discord
      uses: nebularg/actions-discord-webhook@v1
      if: always()
      with:
        webhook_url: ${{ secrets.DISCORD_CI_WEBHOOK }}
        status: ${{ job.status }}
