name: Server

on:
  push:
    branches:
      - main
    paths:
      - server/**
      - Edu.sln
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore
    - name: Test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        dotnet test --no-build --verbosity normal
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        token: ${{ secrets.DOCTL_TOKEN }}
    - name: Update DigitalOcean app spec
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        doctl apps update ${{ secrets.DO_APP_ID }} --spec ./.do/app.yaml
    - name: Send status to Discord
      uses: nebularg/actions-discord-webhook@v1
      if: always()
      with:
        webhook_url: ${{ secrets.DISCORD_CI_WEBHOOK }}
        status: ${{ job.status }}
